#!/bin/bash

# Script to view all generated grid frames (version 2)
echo "Grid Frames Generated (Version 2 - Without Text Overlays)"
echo "=========================================================="
echo ""

# Get the directory of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GRID_DIR="$SCRIPT_DIR/grid_overlays_v2"

echo "Grid frames use dynamic sizing based on element dimensions:"
echo "- Grid cells are minimum 2x the element size"
echo "- Grid cells are at least 1/10 of scene dimensions"
echo "- No text overlays on grids - clean visualization"
echo ""
echo "Grid coordinate format: (row,column)"
echo "- Row 1 = top, increasing downward"
echo "- Column 1 = left, increasing rightward"
echo ""
echo "----------------------------------------"
echo ""

# Summary of grids
echo "Grid Summary:"
echo ""
echo "Scene 1 (0-13s):"
echo "  • Let's     - 10x9 grid  (100x50px element)"
echo "  • start     - 10x9 grid  (100x50px element)"
echo "  • beginning - 9x3 grid   (250x60px element)"
echo ""
echo "Scene 2 (13-30s):"
echo "  • A         - 9x10 grid  (60x60px element)"
echo "  • B         - 9x10 grid  (60x60px element)"
echo "  • C         - 9x10 grid  (60x60px element)"
echo "  • Do        - 10x10 grid (80x50px element)"
echo "  • Re        - 10x10 grid (80x50px element)"
echo "  • Mi        - 10x10 grid (80x50px element)"
echo ""
echo "Scene 3 (30-39s):"
echo "  • Do        - 10x10 grid (80x50px element)"
echo "  • Re        - 10x10 grid (80x50px element)"
echo "  • Mi        - 10x10 grid (80x50px element)"
echo "  • Fa        - 10x10 grid (80x50px element)"
echo "  • Sol       - 10x10 grid (80x50px element)"
echo ""
echo "Scene 4 (39-55s):"
echo "  • deer      - 9x6 grid   (150x60px element)"
echo "  • sun       - 9x8 grid   (120x60px element)"
echo "  • myself    - 10x5 grid  (180x50px element)"
echo "  • run       - 10x9 grid  (100x50px element)"
echo ""
echo "----------------------------------------"
echo ""
echo "Total grids generated: 18"
echo ""
echo "To view all grids in Preview (macOS):"
echo "open $GRID_DIR/*.png"
echo ""
echo "Grid frames location:"
echo "$GRID_DIR/"
echo ""
echo "Prompts added to: prompts.yaml"
echo "Results saved to: $GRID_DIR/overlay_positions.json"